sidebar:
  userName: "Callum J. Hodge"
  profileImage: /images/ProfileImageSmall.jpeg

  sections:
    - title: About Me
      url: "/my-website/#about"
      icon:
        name: LuUser
        package: "react-icons/lu"

    - title: Publications & Research
      url: "/my-website/#publications"
      icon:
        name: LuLibraryBig
        package: "react-icons/lu"

    - title: Research Interests
      url: "/my-website/#research"
      icon:
        name: LuTelescope
        package: "react-icons/lu"

    - title: CV
      url: "/my-website/#cv"
      icon:
        name: LuIdCard
        package: "react-icons/lu"

    - title: Contact
      url: "/my-website/#contact"
      icon:
        name: LuMessageCircle
        package: "react-icons/lu"
