sidebar:
  userName: "Callum J. Hodge"
  profileImage: /images/ProfileImageSmall.jpeg

  sections:
    - title: About Me
      url: "/"
      sectionId: "about"
      icon:
        name: LuUser
        package: "react-icons/lu"

    - title: Publications & Research
      url: "/"
      sectionId: "publications"
      icon:
        name: LuLibraryBig
        package: "react-icons/lu"

    - title: Research Interests
      url: "/"
      sectionId: "research"
      icon:
        name: LuWrench
        package: "react-icons/lu"

    - title: CV
      url: "/"
      sectionId: "cv"
      icon:
        name: LuNewspaper
        package: "react-icons/lu"

    - title: Contact
      url: "/"
      sectionId: "contact"
      icon:
        name: LuMessageCircle
        package: "react-icons/lu"
