sidebar:
  userName: "Callum J. Hodge"
  profileImage: /images/ProfileImageSmall.jpeg

  sections:
    - title: About Me
      url: "#about"
      icon:
        name: LuUser
        package: "react-icons/lu"

    - title: Publications & Research
      url: "#publications"
      icon:
        name: LuLibraryBig
        package: "react-icons/lu"

    - title: Research Interests
      url: "#research"
      icon:
        name: LuTelescope
        package: "react-icons/lu"

    - title: CV
      url: "#cv"
      icon:
        name: LuIdCard
        package: "react-icons/lu"

    - title: Contact
      url: "#contact"
      icon:
        name: LuMessageCircle
        package: "react-icons/lu"
