# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Callum J. Hodge"
  repoUrl: "https://callum-j-hodge.github.io/my-website"
  description: "Fourth-year Physics with Astrophysics Student"
  author: "Callum J. Hodge"
